- name: Deploying monitoring
  hosts: localhost
  become: no
  tasks:
    - name: Deploy the monitoring dashboard
      shell: "gcloud monitoring dashboards create --config-from-file='Dashboard.json'"