---
# Playbook to deploy Ghost and its components
- name: DB install and start
  hosts: localhost
  become: no
  roles:
    - db

- name: Ghost start
  hosts: localhost
  become: no
  roles:
    - ghost
