---
# Playbook to undeploy Ghost and its component
- hosts: localhost
  tasks:
    - name: Print message
      debug:
        msg: "{{ delete_data }}"
      when: "delete_data is defined"

- name: Undeploy ghost and db(optionally)
  hosts: localhost
  become: no
  roles:
    - { role: undeploy_ghost }
    - { role: undeploy_db, when: "delete_data is defined and delete_data=='true'"}