---
all:
 vars:

  # GKE cluster variables
  gcp_project: cosmic-keep-340822              # ID of GCP Project
  gcp_auth_kind: serviceaccount            # Do not change
  gcp_cred_file: cosmic-keep-340822-505b5d9bea15.json    # Path to service account keys (json file downloaded from GCP)

  gcp_zone: us-west1-b
  gcp_image_type: ubuntu_containerd
  gcp_machine_type: e2-small        # Can be changed if necessary
  gcp_disk_size_gb: 10                # Can be changed if necessary
  gcp_initial_node_count: 2            # Number of nodes to create. Can be changed if necessary


  # APP variables
  ghost_ip: 34.82.210.194
  ghost_port: 30007        # Needs to be updated



  # Additional variables
  # ...

  password_user: \$2b\$10\$D4S9fNC2T6TyajSnFpi0R.w0dA79WW7ncmsBNVENJeYnWeL0FrZ7m 
  delete_data: false