- name: Change ip address in jmeter config
  replace: 
    path: tests/completetest.jmx
    regexp: '^(\s*\<stringProp name="HTTPSampler\.domain"\>).*(\<\/stringProp\>)' 
    replace: '\g<1>{{ghost_ip}}\g<2>'


- name: Execute jmeter
  shell: "nohup jmeter -n -t tests/completetest.jmx &>/dev/null &"