- name: Undeploy the object for Ghost
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: ghost-deployment
        namespace: default
        labels:
          app: ghost
          tier: app


- name: Undeploy the Service for Ghost
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: ghost-service
        namespace: default
        labels:
          app: ghost
          tier: app
    wait: yes
    wait_sleep: 10
    wait_timeout: 360